### ISSUE TITLE
Support or change to lowercase hex encoding?

### ISSUE THREAD

**Issue by jessekrubin** [nyurik/sqlite-hashes#12]
encoding the hex-str hashes as uppercase strings (`5A2A20C8D80DF7C21016A56D65A0E296`) instead of lowercase (`5a2a20c8d80df7c21016a56d65a0e296`) seem/feel pretty non-standard in that most hashing things that can give you a hex string will give you the hex string as lowercase. 

Is there a reason that the hex string(s) are encoded uppercase?

FWIW/IMO: I personally find the upper case version harder to read. I also know that squealite has `lower()` so it's not a _huge_ deal. mostly just curious over here.

**Comment by nyurik** [comment]
@jessekrubin I was thinking about it too - at first i had it lowercase but changed it to upper case to be consistent with the built-in `hex()` function.  I agree it is not as readable in some cases, but consistency should take precedence here, esp because the documentation states that it is similar to `hex(md5(...))`

**Comment by nyurik** [comment]
P.S. supporting both cases is a bit tricky because all hashing functions take any number of parameters, and hash all of them.  We could introduce alternative functions like `md5hex_lower`, but this is no different than `lower(md5hex(...))`. Also we could use some sort of a global settings mechanism if it is available (I am not too familiar with it).
